import { useEffect, useMemo, useState } from 'react';
import { FileText, ScrollText, UserCheck } from 'lucide-react';
import type { ComplianceReport, Decision } from '../../data/types';
import { getDecisions, getReports } from '../../lib/api';
import { ReportCard } from '../components/reports/ReportCard';
import { AuditTrailTable } from '../components/reports/AuditTrailTable';
import { VerificationChain } from '../components/reports/VerificationChain';
import { REPORT_TYPE_META } from '../components/reports/reportMeta';

/**
 * Reports — "Evidence & Compliance Center".
 *
 * Every report is AI-generated, evidence-linked and human-verified: the
 * verification chain is the page's spine. Reports download as real PDFs
 * (jspdf), and the audit trail below shows exactly who approved what, when.
 */

type TypeFilter = 'ALL' | ComplianceReport['type'];

const FILTERS: { key: TypeFilter; label: string }[] = [
  { key: 'ALL', label: 'All reports' },
  { key: 'DECISION_AUDIT', label: 'Decision Audit' },
  { key: 'EU_ETS', label: 'EU ETS' },
  { key: 'FUELEU', label: 'FuelEU' },
  { key: 'ESG_QUARTERLY', label: 'ESG' },
  { key: 'IMO_DCS', label: 'IMO DCS' },
];

export function ReportsPage() {
  const [reports, setReports] = useState<ComplianceReport[]>([]);
  const [decisions, setDecisions] = useState<Decision[]>([]);
  const [filter, setFilter] = useState<TypeFilter>('ALL');

  useEffect(() => {
    let alive = true;
    Promise.all([getReports(), getDecisions()]).then(([r, d]) => {
      if (!alive) return;
      setReports(r);
      setDecisions(d);
    });
    return () => { alive = false; };
  }, []);

  const visible = useMemo(() => {
    const list = filter === 'ALL' ? reports : reports.filter((r) => r.type === filter);
    // Drafts (awaiting sign-off) first, then newest.
    return [...list].sort((a, b) => {
      const ad = a.status === 'draft' ? 0 : 1;
      const bd = b.status === 'draft' ? 0 : 1;
      if (ad !== bd) return ad - bd;
      return b.generatedAt.localeCompare(a.generatedAt);
    });
  }, [reports, filter]);

  const counts = useMemo(() => {
    const drafts = reports.filter((r) => r.status === 'draft').length;
    const verified = reports.filter((r) => r.status !== 'draft').length;
    const signed = decisions.filter((d) => d.approval).length;
    return { drafts, verified, signed };
  }, [reports, decisions]);

  const explainerSteps = [
    { key: 'generated' as const, label: 'AI generated', detail: 'Decision engine drafts every report', done: true },
    { key: 'evidence' as const, label: 'Evidence attached', detail: 'Signals, tool calls & regulations linked', done: true },
    { key: 'signoff' as const, label: 'Human sign-off', detail: 'Nothing ships without a named approver', done: true },
  ];

  return (
    <div style={{ padding: '32px 36px', display: 'flex', flexDirection: 'column', gap: 24 }}>
      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
          <div
            style={{
              width: 40, height: 40, borderRadius: 12,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              background: 'rgba(45,212,191,0.10)', border: '1px solid rgba(45,212,191,0.28)',
            }}
          >
            <FileText size={19} style={{ color: '#2DD4BF' }} strokeWidth={1.75} />
          </div>
          <div>
            <div style={{ fontSize: 10, color: '#5A8AB4', textTransform: 'uppercase', letterSpacing: '0.16em', fontWeight: 700 }}>
              Evidence & Audit
            </div>
            <h1 style={{ fontSize: 26, fontWeight: 700, color: '#EAF4FF', lineHeight: 1.1, letterSpacing: '-0.02em', margin: 0 }}>
              Compliance Center
            </h1>
          </div>
        </div>
        <p style={{ fontSize: 13, color: '#8BA8C8', maxWidth: 560, margin: 0 }}>
          Audit-ready evidence packs behind every AI recommendation — generated by agents,
          verified by people, traceable to the signal.
        </p>
      </div>

      {/* Human-in-the-loop explainer strip */}
      <div
        style={{
          display: 'flex', alignItems: 'center', gap: 24, flexWrap: 'wrap',
          padding: '16px 20px', borderRadius: 14,
          background: 'linear-gradient(90deg, rgba(45,212,191,0.06) 0%, rgba(16,32,51,0.6) 60%)',
          border: '1px solid rgba(45,212,191,0.2)',
        }}
      >
        <div style={{ flex: '2 1 420px', minWidth: 0 }}>
          <VerificationChain steps={explainerSteps} />
        </div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 18, flexWrap: 'wrap' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}>
            <UserCheck size={16} style={{ color: '#2DD4BF' }} strokeWidth={1.75} />
            <div>
              <div style={{ fontSize: 16, fontWeight: 700, color: '#EAF4FF', fontVariantNumeric: 'tabular-nums', lineHeight: 1.1 }}>
                {counts.signed}/{decisions.length || '—'}
              </div>
              <div style={{ fontSize: 9.5, fontWeight: 700, color: '#5A8AB4', letterSpacing: '0.1em', textTransform: 'uppercase' }}>
                decisions signed
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 9 }}>
            <ScrollText size={16} style={{ color: '#E8A043' }} strokeWidth={1.75} />
            <div>
              <div style={{ fontSize: 16, fontWeight: 700, color: '#EAF4FF', fontVariantNumeric: 'tabular-nums', lineHeight: 1.1 }}>
                {counts.drafts}
              </div>
              <div style={{ fontSize: 9.5, fontWeight: 700, color: '#5A8AB4', letterSpacing: '0.1em', textTransform: 'uppercase' }}>
                awaiting sign-off
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Type filter */}
      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
        {FILTERS.map((f) => {
          const active = filter === f.key;
          const count = f.key === 'ALL' ? reports.length : reports.filter((r) => r.type === f.key).length;
          const accent = f.key === 'ALL' ? '#2DD4BF' : REPORT_TYPE_META[f.key].color;
          return (
            <button
              key={f.key}
              type="button"
              onClick={() => setFilter(f.key)}
              style={{
                display: 'inline-flex', alignItems: 'center', gap: 7, cursor: 'pointer',
                fontSize: 11.5, fontWeight: 600,
                color: active ? '#07111D' : '#8BA8C8',
                background: active ? accent : 'rgba(255,255,255,0.04)',
                border: `1px solid ${active ? accent : 'rgba(255,255,255,0.09)'}`,
                padding: '7px 13px', borderRadius: 999,
                transition: 'all 200ms ease',
              }}
            >
              {f.label}
              <span
                style={{
                  fontSize: 9.5, fontWeight: 700, fontVariantNumeric: 'tabular-nums',
                  color: active ? '#07111D' : '#5A8AB4',
                  background: active ? 'rgba(7,17,29,0.14)' : 'rgba(255,255,255,0.06)',
                  padding: '1px 7px', borderRadius: 999,
                }}
              >
                {count}
              </span>
            </button>
          );
        })}
      </div>

      {/* Report list */}
      {reports.length === 0 ? (
        <div
          style={{
            padding: '56px 32px', borderRadius: 14, textAlign: 'center',
            background: 'linear-gradient(180deg, #102033 0%, #0E1C2D 100%)',
            border: '1px dashed rgba(45,212,191,0.25)', color: '#5A8AB4', fontSize: 13,
          }}
        >
          Loading compliance reports…
        </div>
      ) : visible.length === 0 ? (
        <div
          style={{
            padding: '40px 32px', borderRadius: 14, textAlign: 'center',
            background: 'linear-gradient(180deg, #102033 0%, #0E1C2D 100%)',
            border: '1px dashed rgba(255,255,255,0.12)', color: '#5A8AB4', fontSize: 13,
          }}
        >
          No {filter === 'ALL' ? '' : `${REPORT_TYPE_META[filter as ComplianceReport['type']].label} `}reports for this period.
        </div>
      ) : (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
          {visible.map((r, i) => (
            <ReportCard key={r.id} report={r} decisions={decisions} index={i} />
          ))}
        </div>
      )}

      {/* Audit trail */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 12, marginTop: 8 }}>
        <div>
          <div style={{ fontSize: 10, color: '#5A8AB4', textTransform: 'uppercase', letterSpacing: '0.16em', fontWeight: 700 }}>
            Accountability ledger
          </div>
          <h2 style={{ fontSize: 18, fontWeight: 700, color: '#EAF4FF', letterSpacing: '-0.015em', margin: '4px 0 0' }}>
            Audit trail — who approved what, when
          </h2>
          <p style={{ fontSize: 12.5, color: '#8BA8C8', margin: '6px 0 0', maxWidth: 680 }}>
            Every recommendation the agents produce stops here until a named human signs it.
            Approvals and overrides are recorded verbatim and flow into the decision-audit evidence packs above.
          </p>
        </div>
        <AuditTrailTable decisions={decisions} />
      </div>
    </div>
  );
}
